# Generated by Django 5.2.9 on 2025-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('applicants_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Active', max_length=20)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
