# Generated by Django 5.2.9 on 2025-12-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeee', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
