# Generated by Django 5.2.9 on 2025-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
