# Generated by Django 5.2.9 on 2025-12-11 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_invitation_token_employee_role_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payroll_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'payroll_month', 'payroll_year')},
        ),
        migrations.CreateModel(
            name='PayrollStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='payroll.payroll')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
