# Generated by Django 5.2.9 on 2025-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0003_employee_invitation_token_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours_decimal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
